"""
FastAPI backend.

Serves both the API and the frontend (single deployment, single URL --
no separate static host needed):
  GET  /                       -- customer chat UI (frontend/index.html)
  GET  /admin                  -- admin reasoning dashboard (frontend/admin.html)
  POST /api/chat                -- send a customer message, get the agent's reply
  GET  /api/sessions/{id}/log  -- full reasoning trace for one session (REST fallback)
  WS   /ws/admin                -- live stream of reasoning events for the admin dashboard
  GET  /api/escalations         -- list of cases currently in manual review
  GET  /api/customers           -- list mock customers (for the demo/admin UI to reference)
  GET  /api/orders              -- list mock orders
"""
import json
import os

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from pydantic import BaseModel

from agent import run_agent_turn, new_session_id
from reasoning_log import register_subscriber, unregister_subscriber, get_all_events, set_main_loop

app = FastAPI(title="Refund Agent API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # demo/local only -- tighten this for any real deployment
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.on_event("startup")
async def capture_main_loop():
    """
    Store a reference to the actual running event loop so reasoning_log.py
    can correctly broadcast to WebSocket clients even when log_event() is
    called from a synchronous route's worker thread (which is how
    /api/chat runs) rather than from the main loop directly.
    """
    import asyncio
    set_main_loop(asyncio.get_running_loop())

FRONTEND_DIR = os.path.join(os.path.dirname(__file__), "..", "frontend")

# In-memory session store: session_id -> conversation history (list of messages).
# Fine for a demo; swap for Redis/DB if this needs to survive a server restart
# or scale past a single process.
_sessions: dict = {}


class ChatRequest(BaseModel):
    session_id: str | None = None
    message: str


class ChatResponse(BaseModel):
    session_id: str
    reply: str


@app.get("/")
def serve_chat_ui():
    return FileResponse(os.path.join(FRONTEND_DIR, "index.html"))


@app.get("/admin")
def serve_admin_ui():
    return FileResponse(os.path.join(FRONTEND_DIR, "admin.html"))


@app.post("/api/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    session_id = req.session_id or new_session_id()
    history = _sessions.get(session_id, [])

    result = run_agent_turn(session_id, history, req.message)
    _sessions[session_id] = result["history"]

    return ChatResponse(session_id=session_id, reply=result["reply"])


@app.get("/api/sessions/{session_id}/log")
def session_log(session_id: str):
    return {"events": get_all_events(session_id)}


@app.get("/api/escalations")
def list_escalations():
    path = os.path.join(os.path.dirname(__file__), "logs", "escalations.json")
    if not os.path.exists(path):
        return {"escalations": []}
    with open(path) as f:
        return {"escalations": json.load(f)}


@app.get("/api/customers")
def list_customers():
    path = os.path.join(os.path.dirname(__file__), "data", "customers.json")
    with open(path) as f:
        return {"customers": json.load(f)}


@app.get("/api/orders")
def list_orders():
    path = os.path.join(os.path.dirname(__file__), "data", "orders.json")
    with open(path) as f:
        return {"orders": json.load(f)}


@app.websocket("/ws/admin")
async def admin_log_stream(websocket: WebSocket):
    """
    Admin dashboard connects here to receive every reasoning-log event in
    real time, as it's generated by any active chat session.
    """
    await websocket.accept()
    register_subscriber(websocket)
    try:
        # Send full history first so a freshly-opened dashboard isn't empty
        for event in get_all_events():
            await websocket.send_json(event)
        while True:
            # Keep the connection alive; we don't expect inbound messages,
            # but we still need to await something or the socket closes.
            await websocket.receive_text()
    except WebSocketDisconnect:
        unregister_subscriber(websocket)


@app.get("/api/health")
def health():
    from llm_client import USE_ANTHROPIC, USE_OPENAI
    if USE_ANTHROPIC:
        mode = "claude"
    elif USE_OPENAI:
        mode = "openai"
    else:
        mode = "mock"
    return {"status": "ok", "llm_mode": mode}
